### ISSUE TITLE
Make e2e tests more sustainable

### ISSUE THREAD

**Issue by agryaznov** [paritytech/ink-waterfall#34]
Currently ink-waterfall tests have the following drawbacks (regarding the CI job running them):

**1. A test could be easily broken by some change on the UI side, which is out of our control, while it would still block all ink! PRs because of non-green CI.**

Currently e2e tests are simply being run versus [currently deployed](https://github.com/paritytech/ink-waterfall/blob/20817b1e1d604b26a3f27e98d2a9620a959aefc2/src/uis/polkadot_js.rs#L1506) version of [polkadot-js](https://polkadot.js.org/apps/). The good effect of this is that it lets us catch any issue which ink! (and pallet_contract) users face while interacting with them on https://polkadot.js.org/apps, which is by now the most likely usage case. However, once these tests run on the CI, this some(not so rare)times [leads](https://github.com/paritytech/ink-waterfall/pull/33) to a PR stuck for ink!, which, again, could be caused by a bug\change on a UI side. So basically we are maintaining tests for the UI part, at the costs of longer PR delivery for our products.

Possible actions to solve this could be:

- Make UI projects run contracts e2e tests (on ink! examples) as part of CI\CD process of their deployment. 
  Solely depends on @jacogr for polkadot-js, and on @statictype for contracts-ui.
- As part of the CI job run on a ink! PR, run ink-waterfall tests versus a concrete UI version, specially deployed for that particular run as part of that CI pipeline. 
- Make ink-waterfall use cargo-contract for interactions with contracts. We could make this option to be used in ink! PR CI jobs. 

**2. Quite unsustainable test results like [this one](https://gitlab.parity.io/parity/mirrors/ink-waterfall/-/jobs/1635180#L3395) are noticed, which generally dissapear after one or a couple of restarts.** 
```
thread 'tests::erc721::erc721_operator_approvals' panicked at 'upload must have succeeded, but events contain only []', src/uis/polkadot_js.rs:470:9
```
or 

```
 thread 'tests::erc1155::erc1155_approvals' panicked at 'upload must have succeeded, but events contain only []', src/uis/polkadot_js.rs:470:9=
```
These ones could suddenly happen on different examples on different runs, and just a restart is an only so far known way to treat this. I think we should look into it and make it more sustainable.

**Comment by jacogr** [comment]
I ripped out all e2e tests on my side around 18 months ago since it adds no benefit to my side. There is one of me with -

- the api
- the util libs
- the apps UI
- the extension
- the cli tools
- the wasm libs
- … I probably forgot some

The “UI” component is one small portion of repos where I’m the only developer, and contracts are not touched at all. 

With a team, yeah sure, but not going to add more to my pile of shit to get done. 

(And I honestly do appreciate issues that have been logged from tests here in the past - they saved me a lot of extra unneeded issues and even fuller queues to look at when all hell would have broken out)

**Comment by jacogr** [comment]
If you are running these on all PRs, make it a nightly job that logs an issue when it fails. CI PR pipeline stays fast. (Proper failures are easily tracked to merges in the last 24)

**Comment by statictype** [comment]
E2E tests for ink! examples in Contracts UI are underway.  I think ink-waterfall should move away from UI testing and only test with `cargo-contract` which now has all the needed features
